In [5]:
#imports

import numpy as np
import pandas as pd


In [6]:
# Refreshing on what [*'anything'] means
arr = ['one','two','three']

print(arr)

print(*arr)

['one', 'two', 'three']
one two three


For understading more about `(*)` please go through this link : [LINK](https://treyhunner.com/2018/10/asterisks-in-python-what-they-are-and-how-to-use-them/), it's very important that you understand what it does before continuing the notebook!!

In [7]:
# numpy random integer generator

rng = np.random.default_rng(0) #Return random integers

s = pd.Series(rng.integers(-10, +10, size=5))
df1 = pd.DataFrame(rng.integers(-10, +10, size =(5,3)), columns=[*'abc'])
df2 = pd.DataFrame(rng.integers(-10, +10, size =(5,3)), columns=[*'def'])


[`rng.integers()`](https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.integers.html)

In [8]:
s

0    7
1    2
2    0
3   -5
4   -4
dtype: int64

In [9]:
df1

a  b   c
0 -10 -9 -10
1  -7  6   2
2   8  0   2
3   9  4   2
4   0  1   8

In [10]:
df2

d   e   f
0  -5   6   3
1 -10  -3   7
2   1 -10   5
3   4   6  -7
4  -9   7 -10

### Fun Part

In [11]:
print(s*df1)  # What in the Lord's Name is Going in Here

    a   b   c   0   1   2   3   4
0 NaN NaN NaN NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN NaN NaN NaN
3 NaN NaN NaN NaN NaN NaN NaN NaN
4 NaN NaN NaN NaN NaN NaN NaN NaN


In [12]:
print(df1+df2)  # Why 

    a   b   c   d   e   f
0 NaN NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN NaN
3 NaN NaN NaN NaN NaN NaN
4 NaN NaN NaN NaN NaN NaN


In [13]:
#Let's throw away the Pandas part !!

df1.values + df2.values  # it works!!!!

array([[-15,  -3,  -7],
       [-17,   3,   9],
       [  9, -10,   7],
       [ 13,  10,  -5],
       [ -9,   8,  -2]])

In [14]:
s.values + df1.values # Returns an ERROR : Oh no no...

ValueError: operands could not be broadcast together with shapes (5,) (5,3) 

In [ ]:
# let's add a new axis to satify broadcasting rules!

s.values[:, None]

array([[ 7],
       [ 2],
       [ 0],
       [-5],
       [-4]])

In [ ]:
#Check if using `None` really add a new axis!!!

print(s.values.shape)

(5,)


In [ ]:
s.values[:, None].shape  # we can see a new axis is added!!

(5, 1)

In [ ]:
s.values[:, None] + df1.values

array([[-3, -2, -3],
       [-5,  8,  4],
       [ 8,  0,  2],
       [ 4, -1, -3],
       [-4, -3,  4]])

In [ ]:
rng = np.random.default_rng(0)

s = pd.Series(rng.integers(-10, +10, size=5))
df1 = pd.DataFrame(rng.integers(-10, +10, size =(5,3)), columns=[*'abc'])
df2 = pd.DataFrame(rng.integers(-10, +10, size =(5,3)), columns=[*'abc'])



In [ ]:
df1

a  b   c
0 -10 -9 -10
1  -7  6   2
2   8  0   2
3   9  4   2
4   0  1   8

In [ ]:
df1.groupby('a').sum()

b   c
a         
-10 -9 -10
-7   6   2
 0   1   8
 8   0   2
 9   4   2

[`.groupby()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html) : A `groupby` operation involves some combination of splitting the object, applying a function, and combining the results

In [ ]:
df1.groupby('a').sum() +df2 # Will this work?


a    b     c
-10 NaN  NaN   NaN
-7  NaN  NaN   NaN
 0  NaN  7.0  11.0
 1  NaN  NaN   NaN
 2  NaN  NaN   NaN
 3  NaN  NaN   NaN
 4  NaN  NaN   NaN
 8  NaN  NaN   NaN
 9  NaN  NaN   NaN

Cells that don't have any matching values with the another DataFrame are filled with `NaN`

In [ ]:
df1.groupby('a').sum().reset_index()+df2 # This works!

a   b   c
0 -15  -3  -7
1 -17   3   9
2   1  -9  13
3  12   6  -5
4   0  11  -8

[`reset_index()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.reset_index.html?highlight=reset_index#pandas.DataFrame.reset_index): Reset the index of the DataFrame, and use the default one instead. 

In [ ]:
rng = np.random.default_rng(0)

s1 = pd.Series(rng.integers(-10, +10, size=4), index=[*'aabb'])
s2 = pd.Series(rng.integers(-10, +10, size=4), index=[*'aabb'])


In [ ]:
s1 # series with 4 elements

a    7
a    2
b    0
b   -5
dtype: int64

In [ ]:
s2

a    -4
a   -10
b    -9
b   -10
dtype: int64

In [ ]:
s1+s2 # when we add ; we return 4 elements too!! 

a     3
a    -8
b    -9
b   -15
dtype: int64

In [ ]:
#Let's Change the index!!

rng = np.random.default_rng(0)

s1 = pd.Series(rng.integers(-10, +10, size=4), index=[*'aaab'])  
s2 = pd.Series(rng.integers(-10, +10, size=4), index=[*'abbb'])

In [ ]:
s1

a    7
a    2
a    0
b   -5
dtype: int64

In [ ]:
s2

a    -4
b   -10
b    -9
b   -10
dtype: int64

In [ ]:
s1+s2 # by default we had 4 elements each in s1 and s2  ; got 6 elements in return! How?

a     3
a    -2
a    -4
b   -15
b   -14
b   -15
dtype: int64

In [ ]:
#Let's Change the index again to see if we can find some more strange behaviour!!

rng = np.random.default_rng(0)

s1 = pd.Series(rng.integers(-10, +10, size=4), index=[*'aabb'])  
s2 = pd.Series(rng.integers(-10, +10, size=4), index=[*'abbb'])

In [ ]:
s1+s2 # returns 8 elements when have 4 elements in each of the two series(s1,s2)!

a     3
a    -2
b   -10
b    -9
b   -10
b   -15
b   -14
b   -15
dtype: int64

In [ ]:
# let's try a good ol' reset_index()!

s1.reset_index()+s2.reset_index() # this returns the same elements as we have defined for our two series but the indexing dosen't make any sense!

index   0
0    aa   3
1    ab  -8
2    bb  -9
3    bb -15

In [ ]:
s1.reset_index(drop=True)+s2.reset_index(drop=True)

0     3
1    -8
2    -9
3   -15
dtype: int64

In [ ]:
# imports 

from numpy import repeat 


`numpy.repeat`:https://numpy.org/doc/stable/reference/generated/numpy.repeat.html

In [ ]:
rng = np.random.default_rng(0)
size = 8
d = {
    'a': repeat([True,False],(size)//2),
     'b': rng.integers(-10,+10, size=size)
}

In [ ]:
df = pd.DataFrame(data=d)

In [ ]:
df

a   b
0   True   7
1   True   2
2   True   0
3   True  -5
4  False  -4
5  False -10
6  False  -9
7  False -10

In [ ]:
# Let's find out all the place where `a` is True and where `a` is False

df.groupby('a').sum()

b
a        
False -33
True    4

In [ ]:
# Let's say we want to find  kurtosis value in the above group-by!


# Method 1 : Using `transform`


df.groupby('a').transform(lambda x: x.kurt()) # This return 8 values , why?

b
0  0.711103
1  0.711103
2  0.711103
3  0.711103
4  3.412305
5  3.412305
6  3.412305
7  3.412305

[`.transform()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.core.groupby.DataFrameGroupBy.transform.html?highlight=transform#pandas.core.groupby.DataFrameGroupBy.transform) : Call function producing a like-indexed DataFrame on each group and return a DataFrame having the same indexes as the original object filled with the transformed values.

In [ ]:
# Method 2 : Using `apply`

df.groupby('a').apply(lambda x: x.kurt()) # now, its getting really bizzare and confusing!

a         b
a                   
False  0.0  3.412305
True   0.0  0.711103

[`.apply()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html): Apply a function along an axis of the DataFrame.

In [ ]:
# Method 3 : Using `agg`

df.groupby('a').agg(lambda x: x.kurt())  # Finally, something that works!!!!

b
a              
False  3.412305
True   0.711103

[`.agg()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.agg.html):Aggregate using one or more operations over the specified axis.

But wait! Do we even know what kurtosis values are ? And, why are we doing this ? 

### The Big Picture:

Maybe its worth to go through all this trouble because the `DataFrame` gives us the ability to store multiple one-dimensional data sets, at the cost of code-complexity!

### Tradeoff : NumPy v/s Python



In [ ]:
# Reason to use Numpy

from time import perf_counter, sleep
from contextlib import contextmanager
from random import randint as py_randint
from numpy.random import randint as np_randint
from numpy import dot as np_dot

### This is just a timer function : N0 need to understand this !!!


@contextmanager
def  timed(msg):
  start = perf_counter()
  try:
      yield
  finally:
      stop = perf_counter()
      print(f'{msg:<24}elasped \N{mathematical bold capital delta}t: {stop-start:.6f}')


#Checking if the timer function works correctly!
with timed('sleep'):
  sleep(1)




sleep                   elasped 𝚫t: 1.001149


In [ ]:
# Global variable are written in all-capital

SIZE = 100_000 # Using underscore for readability purpose

with timed('py: create'):
    py_xs = [py_randint(-10,+10) for _ in range(SIZE)]
    py_ys = [py_randint(-10, +10)for _  in range(SIZE)]


with timed('np: create'):
    np_xs = np_randint(-10, +10, size=SIZE)
    np_ys = np_randint(-10, +10, size=SIZE)

py: create              elasped 𝚫t: 0.285596
np: create              elasped 𝚫t: 0.004485


In [ ]:
## Dot product in python

py_dot = lambda xs,ys: sum(x * y for x,y in zip(xs,ys)) # take each of the value of x's and y's -> pair them up -> multiply them -> sum the result

with timed('py: dot'):
    py_dot(py_xs, py_ys)

with timed('np: dot'):
    np_dot(np_xs, np_ys) # we are almost 70x faster than python

# Mixing numpy + python

with timed('np: dot(py data)'):
    py_dot(np_xs,np_ys) # we can see that we're are losing that speed when we mix Python with Numpy!

py: dot                 elasped 𝚫t: 0.017085
np: dot                 elasped 𝚫t: 0.000793
np: dot(py data)        elasped 𝚫t: 0.024950


### Diggin Deep into NumPy

In [ ]:
from numpy import array

xs = array([0,1,2,3])
# A np.ndarray is an interpreted view of raw memory
print(
    f'xs                                = {xs                                }',
    f'xs.__array_interface__["data"][0] = {xs.__array_interface__["data"][0] }',
    f'xs.dtype                          = {xs.dtype                           }',
    f'xs.shape                          = {xs.shape                           }',
    f'xs.strides                        = {xs.strides                         }',
    sep='\n',
)

xs                                = [0 1 2 3]
xs.__array_interface__["data"][0] = 41000960
xs.dtype                          = int64
xs.shape                          = (4,)
xs.strides                        = (8,)


In [ ]:
#Python

# Python list is some sort of opaque collection of items!
xs = [1,2,3]
ys = [4,5,6]

print(f'xs+ys   = {xs+ys}')
print(f'xs * 3  = {xs * 3}')

xs+ys   = [1, 2, 3, 4, 5, 6]
xs * 3  = [1, 2, 3, 1, 2, 3, 1, 2, 3]


In [ ]:
# Same operations is Numpy

from numpy import array
# `numpy` provides us with a "mathematicial type- what we called vector or matrix or tensor -with corresponding operations "
# np array provide us with : fixed size , dynamic shape , higher-dimensional structure

xs = array([1,2,3])
ys = array([4,5,6])

print(f'xs+ys   = {xs+ys}')
print(f'xs * 3  = {xs * 3}')

xs+ys   = [5 7 9]
xs * 3  = [3 6 9]


In [ ]:
xs = [
    [0,1,2],
    [3,4,5],
    [6,7,8],
]

print(
    f'xs[0][1]  = {xs[0][1]}',
    f'xs[0]     = {xs[0]}',
    f'{[row[1]for row in xs]}', # Accessing column; although it may look like we're providing two coordinates, we're not! we just provide 1 coordinate - its not a 2d structure but a nested list; we're just doing 2 lookups on two list!
    sep='\n',
)

xs[0][1]  = 1
xs[0]     = [0, 1, 2]
[1, 4, 7]


In [ ]:
# Python list is never 2D data but it can be nested , has no mathematical meaning

xs = [
    [0,1,2],
    [3,4,5],
    [6,7,[8,9,[10]]],
]

print(
    f'xs[0][1]       =  {xs[0][1]}',
    f'xs[2][2][2][0] = {xs[2][2][2][0]}',
    sep='\n',
)

xs[0][1]       =  1
xs[2][2][2][0] = 10


In [ ]:
# One major thing that a `Python list` provides which a Numpy `ndarray` dosen't provide us is the ability to update the size!


xs = ys = [1,2,3,4]
xs.append(5)
ys.append(6)


print(
    f'Memory location = {id(xs)}',  # Same memory location for xs and ys
    f'Memory location = {id(ys)}',
    f'xs              = {xs}',
    f'ys              = {ys}',
    sep='\n',
)

Memory location = 139638183600608
Memory location = 139638183600608
xs              = [1, 2, 3, 4, 5, 6]
ys              = [1, 2, 3, 4, 5, 6]


In [ ]:
# Numpy

from numpy import array, hstack


# quick showing of what hstack does

a = np.array((1,2))
b = np.array((3,4))
print(
    f'a               = {a}',
    f'b               = {b}',
    f'np.hstack((a,b))= {np.hstack((a,b))}',
    sep='\n',
)

a               = [1 2]
b               = [3 4]
np.hstack((a,b))= [1 2 3 4]


For more info about `hstack` : [LINK](https://numpy.org/doc/stable/reference/generated/numpy.hstack.html)

In [ ]:
xs = ys = array([0,1,2]) 
xs = hstack([xs,[3]])

print(
    f'xs                                                   = {xs}',
    f'ys                                                   = {ys}',
    f'xs.__array_interface__["data"][0] or Memory location = {xs.__array_interface__["data"][0]}', # xs and ys are at two different blocks of memory unlike python
    f'ys.__array_interface__["data"][0] or Memory location = {ys.__array_interface__["data"][0]}',
    sep='\n',
    
)

xs                                                   = [0 1 2 3]
ys                                                   = [0 1 2]
xs.__array_interface__["data"][0] or Memory location = 41000960
ys.__array_interface__["data"][0] or Memory location = 22985824


### Concluding python v/s numpy

Python `list`:
- fixed "shape" (linear) # Always 1-dimenisonal
- dynamic size

`numpy.ndarry`:
- fixed size
- dynamic shape

In [ ]:
from xarray import DataArray
from numpy.random import default_rng


In [ ]:
img = DataArray(
    data=rng.integers(0,255, size=(3,3), dtype='uint8'),
    dims=[*'xy'],
)

print(
    img,
    f'------------------------------------------------------',
    f'img.sel(x=0)             = {img.sel(x=0)}',
    f'------------------------------------------------------',
    f'img.sel(x=0,y=1)         = {img.sel(x=0,y=1)}',
    f'-------------------------------------------------------',
    f'img.sel(x=[0,1],y=[0,1]) = {img.sel(x=[0,1],y=[0,1])}',
    sep='\n\n',
)

<xarray.DataArray (x: 3, y: 3)>
array([[ 58,  80, 221],
       [ 43, 119, 121],
       [ 49, 207,  77]], dtype=uint8)
Dimensions without coordinates: x, y

------------------------------------------------------

img.sel(x=0)             = <xarray.DataArray (y: 3)>
array([ 58,  80, 221], dtype=uint8)
Dimensions without coordinates: y

------------------------------------------------------

img.sel(x=0,y=1)         = <xarray.DataArray ()>
array(80, dtype=uint8)

-------------------------------------------------------

img.sel(x=[0,1],y=[0,1]) = <xarray.DataArray (x: 2, y: 2)>
array([[ 58,  80],
       [ 43, 119]], dtype=uint8)
Dimensions without coordinates: x, y


[`xarray.DataArray`](https://docs.xarray.dev/en/stable/generated/xarray.DataArray.html): DataArray provides a wrapper around numpy ndarrays that uses labeled dimensions and coordinates to support metadata aware operations.

- Go to official docs to learn more about xarray : https://docs.xarray.dev/en/stable/getting-started-guide/why-xarray.html

In [ ]:
# Some functionalitites of xarray ! 

from xarray import DataArray
from numpy import linspace
from numpy.random import default_rng



rng = default_rng(0)
data= rng.integers(0,255,size=(3,3), dtype='uint8')
img = DataArray(
    data= data,
    dims=[*'xy'],
    coords={ # we can define our own coordinate system
        'x': linspace(10, 20, data.shape[0]),
        'y': linspace(10, 20, data.shape[1]),
    },
)

print(
    img,
    f'------------------------------------------------------',
    img.sel(x=15, y=15), #instead of picking values by default instead we're here asking to return a value that is at a specific location in our defined coordinate system
    f'------------------------------------------------------',
    img.sel(x=15, y=13, method='nearest'), # if we can't find any value at the specified coordinate then return the nearest value
    f'------------------------------------------------------',
    img.interp(x=15, y=range(12,18), method='linear'), # find data at give coordinate and if you're missing data then do a linear interpolation
    sep='\n\n',
    
)


<xarray.DataArray (x: 3, y: 3)>
array([[ 94, 129, 193],
       [216, 206, 234],
       [ 14, 162,  32]], dtype=uint8)
Coordinates:
  * x        (x) float64 10.0 15.0 20.0
  * y        (y) float64 10.0 15.0 20.0

------------------------------------------------------

<xarray.DataArray ()>
array(206, dtype=uint8)
Coordinates:
    x        float64 15.0
    y        float64 15.0

------------------------------------------------------

<xarray.DataArray ()>
array(206, dtype=uint8)
Coordinates:
    x        float64 15.0
    y        float64 15.0

------------------------------------------------------

<xarray.DataArray (y: 6)>
array([212. , 210. , 208. , 206. , 211.6, 217.2])
Coordinates:
    x        int64 15
  * y        (y) int64 12 13 14 15 16 17


[`xarray.DataArray.interp`](https://docs.xarray.dev/en/stable/generated/xarray.DataArray.interp.html#xarray.DataArray.interp):Interpolate a DataArray onto new coordinates

### Why Pandas?

In [ ]:
from pandas import Series
from numpy.random import default_rng

rng = default_rng(0)

s = Series(rng.integers(-10, +10, size=5))

print(
    s,
    s.array,
    s.array._ndarray,
    sep='\n\n'
)

0    7
1    2
2    0
3   -5
4   -4
dtype: int64

<PandasArray>
[7, 2, 0, -5, -4]
Length: 5, dtype: int64

[ 7  2  0 -5 -4]


[`pandas.array`](https://pandas.pydata.org/docs/reference/api/pandas.array.html):Create an array.

In [ ]:
from pandas import Series,date_range
from numpy.random import default_rng

rng = default_rng(0)

idx =  date_range('2022-01-01', periods=5, name='date')
s = Series(rng.integers(-10, +10, size=len(idx)), index=idx)

print(
    s,
    f'------------------------------------------------------',
    s.array,
    f'------------------------------------------------------',
    s.index,
    f'------------------------------------------------------',
    s['2022-01-01'],
    f'------------------------------------------------------',
    s['2022-01-01':],# Value from 1st of Jan till whatever has been captured!
    sep='\n\n',

)

date
2022-01-01    7
2022-01-02    2
2022-01-03    0
2022-01-04   -5
2022-01-05   -4
Freq: D, dtype: int64

------------------------------------------------------

<PandasArray>
[7, 2, 0, -5, -4]
Length: 5, dtype: int64

------------------------------------------------------

DatetimeIndex(['2022-01-01', '2022-01-02', '2022-01-03', '2022-01-04',
               '2022-01-05'],
              dtype='datetime64[ns]', name='date', freq='D')

------------------------------------------------------

7

------------------------------------------------------

date
2022-01-01    7
2022-01-02    2
2022-01-03    0
2022-01-04   -5
2022-01-05   -4
Freq: D, dtype: int64


In [ ]:
# The index is how we access values

from pandas.core import series
from pandas import Series,date_range
from numpy.random import default_rng
from numpy import linspace, array

rng = default_rng(0)

# Uncomment the labels:'idx' one by one to see the how the miss-match occurs!
idx = linspace(-20, +20,5)
idx = linspace(-20, +20,5, dtype=int)
idx = array([-1,0,1,2,3,4], dtype=float)
#idx = [*'abcde']
#idx = [*'.a...c.']
#idx = [*'.aa.cc.']
#idx = [*'.ac.ac.']

s = Series(rng.integers(-10, +10, size=len(idx)), index=idx)

print(
    s,
    f'------------------------------------------------------',
    s.index,
    f'------------------------------------------------------',
    s[0], # value at label 0
    f'------------------------------------------------------',
    s[0:3], # Give values of label 0 till label 3, which is just that value'0'
    f'------------------------------------------------------',
    f'{len(s.array[0:3]) }\n{len(s[0:3])}', # Asking for values from 0-3 from pandas array v/s the values that are in label location 0-3
    f'------------------------------------------------------',
    s.loc[0], # if we want to use "index" : labels
    s.loc[0:3],
    f'------------------------------------------------------',
    s.iloc[0], # use position instead of "index"; we don't use the index!
    s.iloc[0:3],
    f'------------------------------------------------------',
    # Comparing s.array v/s s.iloc
    s.iloc[0:3], # one thing to noice is that `interval notation ":"` includes the end-point which is not the case with python!
    s.array[0:3],
    f'------------------------------------------------------',
    s.iloc[0:3+1],
    s.array[0:3+1],
    sep='\n\n',

)

-1.0     7
 0.0     2
 1.0     0
 2.0    -5
 3.0    -4
 4.0   -10
dtype: int64

------------------------------------------------------

Float64Index([-1.0, 0.0, 1.0, 2.0, 3.0, 4.0], dtype='float64')

------------------------------------------------------

2

------------------------------------------------------

0.0    2
1.0    0
2.0   -5
3.0   -4
dtype: int64

------------------------------------------------------

3
4

------------------------------------------------------

2

0.0    2
1.0    0
2.0   -5
3.0   -4
dtype: int64

------------------------------------------------------

7

-1.0    7
 0.0    2
 1.0    0
dtype: int64

------------------------------------------------------

-1.0    7
 0.0    2
 1.0    0
dtype: int64

<PandasArray>
[7, 2, 0]
Length: 3, dtype: int64

------------------------------------------------------

-1.0    7
 0.0    2
 1.0    0
 2.0   -5
dtype: int64

<PandasArray>
[7, 2, 0, -5]
Length: 4, dtype: int64


In [ ]:
# The index is how we access values

from pandas.core import series
from pandas import Series,date_range
from numpy.random import default_rng
from numpy import linspace, array

rng = default_rng(0)

# Uncomment the labels:'idx' one by one to see the how the miss-match occurs!

idx = [*'abcde']
#idx = [*'.a...c.']
#idx = [*'.aa.cc.']
#idx = [*'.ac.ac.']

s = Series(rng.integers(-10, +10, size=len(idx)), index=idx)

print(
    s,
    f'------------------------------------------------------',
    s.index,
    f'------------------------------------------------------',
    #s.loc['a':'c'+1], # This will return an error because the index does not have some sort of order associated with it 
                       # and one of the main reason we had to include "end-point" in Pandas
    f'------------------------------------------------------',
    s.loc['a':'c'],
    sep="\n\n",

)

a    7
b    2
c    0
d   -5
e   -4
dtype: int64

------------------------------------------------------

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

------------------------------------------------------

------------------------------------------------------

a    7
b    2
c    0
dtype: int64


### Let's try different index to understand the bhehaviour of `.loc`

In [ ]:
#idx = [*'abcde']
idx = [*'.a...c.']
#idx = [*'.aa.cc.']
#idx = [*'.ac.ac.']

s = Series(rng.integers(-10, +10, size=len(idx)), index=idx)

print(
    s,
    f'------------------------------------------------------',
    s.index,
    f'------------------------------------------------------',
    #s.loc['a':'c'+1], # This will return an error because the index does not have some sort of order associated with it 
                       # and one of the main reason we had to include "end-point" in Pandas
    f'------------------------------------------------------',
    s.loc['a':'c'],
    sep="\n\n",
)

.   -10
a    -9
.   -10
.    -7
.     6
c     2
.     8
dtype: int64

------------------------------------------------------

Index(['.', 'a', '.', '.', '.', 'c', '.'], dtype='object')

------------------------------------------------------

------------------------------------------------------

a    -9
.   -10
.    -7
.     6
c     2
dtype: int64


In [ ]:
#idx = [*'abcde']
#idx = [*'.a...c.']
idx = [*'.aa.cc.']
#idx = [*'.ac.ac.']

s = Series(rng.integers(-10, +10, size=len(idx)), index=idx)

print(
    s,
    f'------------------------------------------------------',
    s.index,
    f'------------------------------------------------------',
    #s.loc['a':'c'+1], # This will return an error because the index does not have some sort of order associated with it 
                       # and one of the main reason we had to include "end-point" in Pandas
    f'------------------------------------------------------',
    s.loc['a':'c'],
    sep="\n\n",
)

.    0
a    2
a    9
.    4
c    2
c    0
.    1
dtype: int64

------------------------------------------------------

Index(['.', 'a', 'a', '.', 'c', 'c', '.'], dtype='object')

------------------------------------------------------

------------------------------------------------------

a    2
a    9
.    4
c    2
c    0
dtype: int64


In [ ]:
# This will return an error!

#idx = [*'abcde']
#idx = [*'.a...c.']
#idx = [*'.aa.cc.']
idx = [*'.ac.ac.']  # Can't differentiate b/w which 'a' and 'c' we're asking for!

s = Series(rng.integers(-10, +10, size=len(idx)), index=idx)

print(
    s,
    f'------------------------------------------------------',
    s.index,
    f'------------------------------------------------------',
    #s.loc['a':'c'+1], # This will return an error because the index does not have some sort of order associated with it 
                       # and one of the main reason we had to include "end-point" in Pandas
    f'------------------------------------------------------',
    s.loc['a':'c'],
    sep="\n\n",
)

KeyError: ignored

### Different Types of Index 

In [ ]:
from pandas import Series, date_range, interval_range, period_range
from numpy import arange
from numpy.random import default_rng

rng = default_rng(0)

idx = arange(0,5)


s = Series(rng.integers(-10, +10, size=len(idx)), index=idx)

print(
    s.index,
    f'-------------------',
    s.index.array ,
    sep='\n\n',
)

Int64Index([0, 1, 2, 3, 4], dtype='int64')

-------------------

<PandasArray>
[0, 1, 2, 3, 4]
Length: 5, dtype: int64


In [ ]:

rng = default_rng(0)

idx = range(0, 10, 2 )

s = Series(rng.integers(-10, +10, size=len(idx)), index=idx)


print(
    s.index,
    f'-------------------',
    s.index.array ,
    sep='\n\n',
)


RangeIndex(start=0, stop=10, step=2)

-------------------

<PandasArray>
[0, 2, 4, 6, 8]
Length: 5, dtype: int64


In [ ]:
rng = default_rng(0)

idx = arange(0, 5 )

s = Series(rng.integers(-10, +10, size=len(idx)), index=idx)


print(
    s.index,
    f'-------------------',
    s.index.array ,
    sep='\n\n',
)


Int64Index([0, 1, 2, 3, 4], dtype='int64')

-------------------

<PandasArray>
[0, 1, 2, 3, 4]
Length: 5, dtype: int64


`date_range`: https://pandas.pydata.org/docs/reference/api/pandas.date_range.html

In [ ]:
rng = default_rng(0)

# Uncomment each 'idx' one by one!

#idx = date_range('2022-01-01', periods=5, name='date')
idx = date_range('2022-01-01', periods=5, freq='2T', name='date')

s = Series(rng.integers(-10, +10, size=len(idx)), index=idx)


print(
    s.index,
    f'-------------------',
    s.index.array ,
    sep='\n\n',
)


DatetimeIndex(['2022-01-01 00:00:00', '2022-01-01 00:02:00',
               '2022-01-01 00:04:00', '2022-01-01 00:06:00',
               '2022-01-01 00:08:00'],
              dtype='datetime64[ns]', name='date', freq='2T')

-------------------

<DatetimeArray>
['2022-01-01 00:00:00', '2022-01-01 00:02:00', '2022-01-01 00:04:00',
 '2022-01-01 00:06:00', '2022-01-01 00:08:00']
Length: 5, dtype: datetime64[ns]


`inerval_range`: https://pandas.pydata.org/docs/reference/api/pandas.interval_range.html

In [ ]:
rng = default_rng(0)

# Uncomment each 'idx' one by one!

#idx = interval_range(0,5, name='value')
idx = interval_range(0,10, freq=2, closed='left', name='value')
s = Series(rng.integers(-10, +10, size=len(idx)), index=idx)


print(
    s.index,
    f'-------------------',
    s.index.array ,
    sep='\n\n',
)


IntervalIndex([[0, 2), [2, 4), [4, 6), [6, 8), [8, 10)], dtype='interval[int64, left]', name='value')

-------------------

<IntervalArray>
[[0, 2), [2, 4), [4, 6), [6, 8), [8, 10)]
Length: 5, dtype: interval[int64, left]


`period_range` : https://pandas.pydata.org/docs/reference/api/pandas.interval_range.html

In [ ]:
rng = default_rng(0)

# Uncomment each 'idx' one by one!
idx = period_range('2022Q1', periods=3, freq='Q', name='quater')
s = Series(rng.integers(-10, +10, size=len(idx)), index=idx)


print(
    s.index,
    f'-------------------',
    s.index.array ,
    sep='\n\n',
)

PeriodIndex(['2022Q1', '2022Q2', '2022Q3'], dtype='period[Q-DEC]', name='quater')

-------------------

<PeriodArray>
['2022Q1', '2022Q2', '2022Q3']
Length: 3, dtype: period[Q-DEC]


 All these 'idx' may let you believe that Pandas  `index` is data but actually it isn't  data. It is something that we can convert to data. Pandas `index` is actually a mechanism 

### Pandas `index` is not actually data!

In [ ]:
from pandas import RangeIndex

idx = RangeIndex(0,100)
print(
    idx,
    f'****************************',
    idx.has_duplicates,
    f'****************************',
    idx.is_monotonic,
    f'****************************',
    idx.is_unique,
    sep='\n\n'
)

RangeIndex(start=0, stop=100, step=1)

****************************

False

****************************

True

****************************

True


In [ ]:
idx = RangeIndex(0,100_000_000_000_000) # If it was data then there is no way we could've stored values upto this big of a number!
print(
    idx,
    f'****************************',
    idx.has_duplicates,
    f'****************************',
    idx.is_monotonic,
    f'****************************',
    idx.is_unique,
    sep='\n\n'
)

RangeIndex(start=0, stop=100000000000000, step=1)

****************************

False

****************************

True

****************************

True


In [ ]:
idx = RangeIndex(10, 20, 5)
print(
    idx,
    f'****************************',
    idx.has_duplicates,
    f'****************************',
    idx.is_monotonic,
    f'****************************',
    idx.is_unique,
    f'****************************',
    idx.get_loc, # Return what one-key transistion into when we want to find a physical position
    f'****************************',
    idx.get_loc(10), # This is interpreted as : the value 10 on the range-index from 10 upto 20 with step size of 5 will get the value of position at the start which is 0!
    f'****************************',
    idx.slice_locs(10,13),
    f'****************************',
    idx.get_indexer(range(10, 30, 5)), # -1 means data is not located and we might need to do some NaN filling for these positon!

    sep='\n\n'
)

RangeIndex(start=10, stop=20, step=5)

****************************

False

****************************

True

****************************

True

****************************

<bound method RangeIndex.get_loc of RangeIndex(start=10, stop=20, step=5)>

****************************

0

****************************

(0, 1)

****************************

[ 0  1 -1 -1]


If you wanna know more about `index methods` : https://pandas.pydata.org/docs/reference/indexing.html

In [ ]:
# Diving more in-depth into indices in Pandas


from pandas import(
    RangeIndex,
    Int64Index,Float64Index, Index,
    IntervalIndex, DatetimeIndex, PeriodIndex,
)

from pandas import Series
from pandas import(
    interval_range, date_range, period_range,
    to_datetime, to_timedelta,
)
from numpy.random import default_rng
from functools import reduce
from operator import and_ 


rng = default_rng(0)

indices = [
    (range(5),                                    RangeIndex),
    (range(5, 10),                                RangeIndex),
    (range(5, 15, 2),                             RangeIndex),
    ([0, 1, 2, 3, 5],                             Int64Index),
    ([0, 1, 2, 3, 5.0],                           Float64Index),
    ([*'abcde'],                                  Index),
    (interval_range(0, 10 , 5, closed='left'),    IntervalIndex),
    (date_range('2022-01-01', periods=5),         DatetimeIndex),
    (to_datetime('2022-01-01')
    + to_timedelta([0, 0, 1, 1, 2], unit='D'),    DatetimeIndex),
    (period_range('2022Q1', periods=5, freq='Q'), PeriodIndex),
]

#iterating through each one of these indices

for idx, typ in indices:
    s = Series(rng.integers(-10, +10, size=len(idx)), index=idx)
    assert isinstance(s.index, typ)

for idx, _ in indices:
    s = Series(rng.integers(-10, +10, size=len(idx)), index=idx)
    print(
        s.index,
        f's.index.get_loc(s.index[0]){s.index.get_loc(s.index[0])}',
        f's.index.is_monotonic       {s.index.is_monotonic}',
        f's.index.is_unique          {s.index.is_unique}',
        f's.index.has_duplicates     {s.index.has_duplicates}',
        sep='\n', end='\n\n',
        
    )



RangeIndex(start=0, stop=5, step=1)
s.index.get_loc(s.index[0])0
s.index.is_monotonic       True
s.index.is_unique          True
s.index.has_duplicates     False

RangeIndex(start=5, stop=10, step=1)
s.index.get_loc(s.index[0])0
s.index.is_monotonic       True
s.index.is_unique          True
s.index.has_duplicates     False

RangeIndex(start=5, stop=15, step=2)
s.index.get_loc(s.index[0])0
s.index.is_monotonic       True
s.index.is_unique          True
s.index.has_duplicates     False

Int64Index([0, 1, 2, 3, 5], dtype='int64')
s.index.get_loc(s.index[0])0
s.index.is_monotonic       True
s.index.is_unique          True
s.index.has_duplicates     False

Float64Index([0.0, 1.0, 2.0, 3.0, 5.0], dtype='float64')
s.index.get_loc(s.index[0])0
s.index.is_monotonic       True
s.index.is_unique          True
s.index.has_duplicates     False

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
s.index.get_loc(s.index[0])0
s.index.is_monotonic       True
s.index.is_unique          True
s.index.has_d

In [ ]:
# Let's see all the methods that our indices support!

methods = {
    frozenset(
        x
        for x 
        in dir(Series(rng.integers(-10, +10, size=len(idx)), index=idx).index)
        if not x.startswith('__')
    )
    for idx, _ in indices
}
print(
    f'methods={methods}',
    f'sorted(reduce(and_, methods))={sorted(reduce(and_, methods))}',
    sep='\n\n',
)

methods={frozenset({'year', 'to_flat_index', '_get_reconciled_name_object', 'ndim', 'is_numeric', '_typ', 'isin', '_convert_tolerance', '_summary', '_find_common_type_compat', 'array', '_reduce', 'isnull', 'factorize', '_dir_deletions', '_format_attrs', 'sort_values', '_map_values', '_format_space', '_maybe_convert_timedelta', 'union', '_get_attributes_dict', '_field_ops', '_get_indexer', '_na_value', 'get_indexer_non_unique', 'day_of_year', 'insert', '_get_delete_freq', '_intersection_via_get_indexer', '_values', 'view', '_isnan', 'repeat', 'sortlevel', 'to_numpy', '_engine', 'is_all_dates', '_get_join_target', 'difference', '_hidden_attrs', '_data_cls', '_supports_partial_string_indexing', '_parsed_string_to_bounds', 'asfreq', 'isna', 'day_of_week', 'nunique', 'astype', '_get_values_for_loc', '_name', '_simple_new', '_unary_method', '_join_monotonic', 'fillna', '_convert_slice_indexer', '_is_memory_usage_qualified', '_maybe_disable_logical_methods', '_accessors', 'format', 'notnull',

### Why is it hard to create our own Index then use Pandas default ones!

In [ ]:
# Example of trying to create our own index ; in this case a `symmetrical Index`
# A symmetrical index will return the absolute value !


from pandas import Series, Int64Index
from numpy.random import default_rng
from itertools import chain 

############################################
'''
chain() function
It is a function that takes a series of iterables and returns one iterable. It groups all the iterables together and produces a single iterable as output. 

This what chain does: 

def chain(*iterables):
     for it in iterables:
       for each in it:
           yield each
'''
############################################


rng = default_rng(0)

class SymmetricIndex(Int64Index):
    def get_loc(self,key):
        return super().get_loc(abs(key))


idx1 = SymmetricIndex([0,2,4])
s1 = Series(rng.integers(-10, +10, size=len(idx1)), index=idx1)

idx2 = [-4, -3, -2, -1, 0, 1, 2, 3, 4]
s2 = Series(rng.integers(-10, +10, size=len(idx2)), index=idx2)

print(
    idx1,
    f'*************************',
    s1,
    f'*************************',
    s1.index,
    f'*************************',
    f's1.index.get_loc(2)={s1.index.get_loc(2)}\n s1.index.get_loc(-2)={s1.index.get_loc(-2)}',
    f'*************************',
    f's1.loc[2]={s1.loc[2]}\n s1.loc[-2]={s1.loc[-2]}',
    f'*************************',
    s2,
    f'*************************',
    s1+s2,
    sep='\n',
)

SymmetricIndex([0, 2, 4], dtype='int64')
*************************
0    7
2    2
4    0
dtype: int64
*************************
SymmetricIndex([0, 2, 4], dtype='int64')
*************************
s1.index.get_loc(2)=1
 s1.index.get_loc(-2)=1
*************************
s1.loc[2]=2
 s1.loc[-2]=2
*************************
-4    -5
-3    -4
-2   -10
-1    -9
 0   -10
 1    -7
 2     6
 3     2
 4     8
dtype: int64
*************************
-4    NaN
-3    NaN
-2    NaN
-1    NaN
 0   -3.0
 1    NaN
 2    8.0
 3    NaN
 4    8.0
dtype: float64


### Let's check what's happen in Pandas Library when we try to add two series `s1+s2`

- **Don't run this on google colab as the Python version is still 3.7 in it !**


In [83]:
# Make sure you're running Python version 3.8 or above
# You can un-comment all the code below by selecting all the text and  pressing `CTRL + /` on Windows/Linux or `Command + /` on Mac



from contextlib import contextmanager
from sys import gettrace, settrace
from pandas import DataFrame, Series, date_range
from numpy.random import default_rng
from pathlib import Path

@contextmanager
def tracing():
    old_trace = gettrace()
    depth, frames = 0, []
    def trace(frame, event, arg):
        nonlocal depth
        filename = frame.f_code.co_filename
        if filename.startswith('<'): return
        filename = Path(filename)
        # Use `!pip show pandas` to get your own pandas path!
        if not filename.is_relative_to(base_dir := Path('/home/vishu/mambaforge/envs/jlab/lib/python3.10/site-packages/pandas').expanduser()):
          return      
        if event == 'return':
            depth -= 1
        if event == 'call':
            depth += 1
            fr = filename.relative_to(base_dir), frame.f_lineno, frame.f_code.co_name, depth
            frames.append(fr)
            return trace
    settrace(trace)
    try:
      yield lambda: DataFrame(frames, columns='filename lineno function depth'.split()) 
    finally:
      settrace(old_trace)

            
rng = default_rng(0)

idx1 = date_range('2022-01-01', periods=5, name='date')
s1 = Series(rng.integers(-10, +10, size=len(idx1)), index=idx1)

idx2 = date_range('2022-01-02', periods=5, name='date')
s2 = Series(rng.integers(-10, +10, size=len(idx2)), index=idx2)


print(
  s1,
  s2,
  sep='\n\n'
)

with tracing() as get_df:
    s1 + s2


df = get_df()


print(
    df, # around 530 function calls to capture s1+s2
    df[df['depth']<=5],
    df[df['filename'].apply(lambda x: x.is_relative_to('core/indexes'))], # around 116 calls related to index in here!
    sep='\n\n',
      
)



date
2022-01-01    7
2022-01-02    2
2022-01-03    0
2022-01-04   -5
2022-01-05   -4
Freq: D, dtype: int64

date
2022-01-02   -10
2022-01-03    -9
2022-01-04   -10
2022-01-05    -7
2022-01-06     6
Freq: D, dtype: int64
                     filename  lineno               function  depth
0          core/ops/common.py      55             new_method      1
1      core/dtypes/generic.py      43                 _check      2
2      core/dtypes/generic.py      43                 _check      2
3      core/dtypes/generic.py      43                 _check      2
4           core/arraylike.py      98                __add__      2
..                        ...     ...                    ...    ...
533            core/series.py     640                   name      7
534     core/dtypes/common.py    1721  validate_all_hashable      8
535     core/dtypes/common.py    1740              <genexpr>      9
536  core/dtypes/inference.py     321            is_hashable     10
537     core/dtypes/common.py   

### `.index` is operative metadata with well defined semantics (in terms of data operations)

In [ ]:
from pandas import Series
from numpy.random import default_rng
from string import ascii_lowercase

rng = default_rng(0)
size=10_000

s1 = Series(
    data=rng.integers(-10, +10, size=size),
    index=rng.choice([*ascii_lowercase], size=size),
    name='series1'
)
#we can attach meta-data to our series using `.attrs()`
s1.attrs['source'] = ...
s1.attrs['author'] = ...

s2 = Series(
    data=rng.integers(-10, +10, size=size),
    index=rng.choice([*ascii_lowercase], size=size),
    name='series2'
)
s2.attrs['source'] = ...
s2.attrs['date'] = ...

# And this meta-data will be preserved through operations!

print(
    s1.head(3),
    f'***************************************',
    f's1.attrs={s1.attrs}',
    f'***************************************',
    f's1.groupby(s1.index).mean().head(3)={s1.groupby(s1.index).mean().head(3)}',
    f'***************************************',
    f's1.groupby(s1.index).mean().attrs()={s1.groupby(s1.index).mean().attrs}',
    f'***************************************',
    f'(s1+s2).dropna().head(3).attrs={(s1+s2).dropna().head(3).attrs}',
    f'***************************************',
    f'(s2+s1).dropna().head(3).attrs={(s2+s1).dropna().head(3).attrs}',
    f'***************************************',
    f'(s1+s2).name={(s1+s2).name}',
    f'***************************************',
    f'(s2+s1).name={(s2+s1).name}',
    f'***************************************',
    f's2.loc[s1[s1>0].index].attrs={s2.loc[s1[s1>0].index].attrs}',
    f'***************************************',
    f's2.loc[s1[s1>0].index].name={s2.loc[s1[s1>0].index].name}',
    
    
    
    sep='\n\n',
)

r    7
x    2
m    0
Name: series1, dtype: int64

***************************************

s1.attrs={'source': Ellipsis, 'author': Ellipsis}

***************************************

s1.groupby(s1.index).mean().head(3)=a   -0.626632
b    0.219697
c   -0.590551
Name: series1, dtype: float64

***************************************

s1.groupby(s1.index).mean().attrs()={'source': Ellipsis, 'author': Ellipsis}

***************************************

(s1+s2).dropna().head(3).attrs={'source': Ellipsis, 'author': Ellipsis}

***************************************

(s2+s1).dropna().head(3).attrs={'source': Ellipsis, 'date': Ellipsis}

***************************************

(s1+s2).name=None

***************************************

(s2+s1).name=None

***************************************

s2.loc[s1[s1>0].index].attrs={'source': Ellipsis, 'date': Ellipsis}

***************************************

s2.loc[s1[s1>0].index].name=series2


Now, this kind of metadata(authors, date...) has no well-defined semantics in-terms of the operations of the series , in other words, if we add these two series together what we do with the metadata?Do we merge them ? If we have two sources with each representing a string as filename then do we return a set of those strings or return a list of those filenames or we take the bigger of two filenames?If they are two dates or two authors then what do we do?

But there are opertaions that we can perform on this pandas series where the metadata that we had for that pandas series namely the attributes and name of that series may or may not be preserved and is not well-defined,whereas, **Pandas Index is always well-defined in-terms of the operations** because the opertations are defined in-terms of Index. Hence, `pandas.index` is the metadata that will be preserved through transformation that we performs on our data because those transformation are defined on how they change the index.

### Rules of promotion in Numpy!



In [ ]:
# But before we discuss more about pandas index , let's talk about `numpy` 

In [ ]:
from numpy import array, equal, allclose, meshgrid, log, exp
x = 2**53
xs = array([x,x+1,x+2,x+3]) # created a numpy ndarray of 4 integers values
# We're just taking a round trip to the original value 
'''
# Run this basic example to see what we're talking about!
a = [1,2,3]
b = log(exp(a))

print(a,
      b,
      sep='\n\n',)
'''
# We're just taking a round trip to the original value by doing : log(exp('values'))
ys = exp(log(xs)) # took the 4 integers value from above then we take the logrithim and exponentiate them!(we get the orignial value back but instead of int we will have float values!)


print(
    f'{(xs[0]==xs).all()}', # Are all values in our list equal to first value ?                     :-> False
    f'{equal(*meshgrid(xs, xs)).all()}', # Is every value equal every other value ?                 :-> False
    f'{allclose(*meshgrid(xs, xs), atol=1, rtol=0)}', # Is every value close to every other value ? :-> False
    xs,
    sep='\n', end='\n\n',
)

# But we we do some promotion to our int values(xs) and convert them into float values(ys) then:
print(
    f'{(ys[0]==ys).all()}', # Are all values in our list equal to first value ?                     :-> True
    f'{equal(*meshgrid(ys, ys)).all()}', # Is every value equal every other value ?                 :-> True
    f'{allclose(*meshgrid(ys, ys), atol=1, rtol=0)}', # Is every value close to every other value ? :-> True
    ys,
    sep='\n', end='\n\n',
)

False
False
False
[9007199254740992 9007199254740993 9007199254740994 9007199254740995]

True
True
True
[9.00719925e+15 9.00719925e+15 9.00719925e+15 9.00719925e+15]



Thus , by applying some promotion to our int-values(xs) to get float values(ys), we lost the ability to store the distinction b/w these 4 float values because we are currently working with 2^53 meaning IEEE754 dot precision floating point values, we don't have the ability to precisely store that last digit.

- `all()`: https://numpy.org/doc/stable/reference/generated/numpy.all.html

- `allclose()`: https://numpy.org/doc/stable/reference/generated/numpy.allclose.html

- `meshgrid()`: https://numpy.org/doc/stable/reference/generated/numpy.meshgrid.html

- `IEEE754` : https://en.wikipedia.org/wiki/IEEE_754

### Promotion with associated loss of precision happens easily in pandas and can be very tricky to avoid!

In [ ]:
from pandas import Series
from numpy import int64

x= 2**53

# Two same value series just differently indexed..

s1 = Series([x, x+1, x+2, x+3], dtype=int64, index=range(4))
s2 = Series([x, x+1, x+2, x+3], dtype=int64, index=range(1, 4+1))

print(s1,s2,
      f'**********************************',
      f'(s1.values == s2.values).all()={(s1.values == s2.values).all()}', # Do both series contain the same values?     :-> True
      f'**********************************',
      f'(s1.index == s2.index).all()={(s1.index == s2.index).all()}',     # Are indicies the same for both series ?     :-> False
      f'**********************************',
      s1 + s2,                                                            # This  will do an index-align sum, which will give NaN where thigns are missing
      f'**********************************',
      (s1 + s2).dtype,                                                    # Due to NaN it will convert from int64 to Float64
      f'**********************************',
      s1.add(s2, fill_value=0),                                           # Maybe if we replace the NaN values by `0`, will it preserve the int64? :-> No!, It will not
      f'**********************************',
      s1.add(s2, fill_value=0).dtype,
      sep='\n',
    
)

0    9007199254740992
1    9007199254740993
2    9007199254740994
3    9007199254740995
dtype: int64
1    9007199254740992
2    9007199254740993
3    9007199254740994
4    9007199254740995
dtype: int64
**********************************
True
**********************************
False
**********************************
0             NaN
1    1.801440e+16
2    1.801440e+16
3    1.801440e+16
4             NaN
dtype: float64
**********************************
float64
**********************************
0    9.007199e+15
1    1.801440e+16
2    1.801440e+16
3    1.801440e+16
4    9.007199e+15
dtype: float64
**********************************
float64


### Let's take a look at Numpy Broadcasting to better understand index alignment 

- Numpy Broadcasting is about taking two dissimilar shaped dataset and figuring out how to match them up so a operation performed on them make sense!
- `numpy broadcasting`: https://numpy.org/doc/stable/user/basics.broadcasting.html

- `.round()`: https://numpy.org/doc/stable/reference/generated/numpy.round_.html

In [ ]:
from numpy import newaxis
from numpy.random import default_rng

rng = default_rng(0)

xs = rng.normal(size=(2, 3, 4)).round(1)  #:-> shape(2,3,4)
'''
Uncomment `ys` values 1-by-1 to see which returns an error and which dosen't
'''
#ys = rng.normal(size=(2)).round(1)   #:-> shape(2,)   (broadcasting error) 

#to avoid broadcast error lets try :

#ys = rng.normal(size=(2,3)).round(1) #:-> shape(2,3) (broadcasting error)
#ys = rng.normal(size=(3,4)).round(1) #:-> shape(3,4) This will work!
# Using `newaxis` to avoid broadcasting error

#ys = rng.normal(size=(2)).round(1)[:, newaxis, newaxis] #:-> shape(2,1,1) Will work!

print(
    f'xs.shape={xs.shape}',
    f'ys.shape={ys.shape}',
    xs,
    ys,
    xs + ys, # Return `broadcasting error!` 
    sep='\n{}\n'.format('\N{box drawings light horizontal}' * 40),
)

xs.shape=(2, 3, 4)
────────────────────────────────────────
ys.shape=(4,)
────────────────────────────────────────
[[[ 0.1 -0.1  0.6  0.1]
  [-0.5  0.4  1.3  0.9]
  [-0.7 -1.3 -0.6  0. ]]

 [[-2.3 -0.2 -1.2 -0.7]
  [-0.5 -0.3  0.4  1. ]
  [-0.1  1.4 -0.7  0.4]]]
────────────────────────────────────────
[ 0.9  0.1 -0.7 -0.9]
────────────────────────────────────────
[[[ 1.   0.  -0.1 -0.8]
  [ 0.4  0.5  0.6  0. ]
  [ 0.2 -1.2 -1.3 -0.9]]

 [[-1.4 -0.1 -1.9 -1.6]
  [ 0.4 -0.2 -0.3  0.1]
  [ 0.8  1.5 -1.4 -0.5]]]


### Rules of Broadcasting in Numpy

In [ ]:
# Here is how rules of `Brodcasting` works:
'''
Take the dim. of the structure you're looking at (in our example: xs and ys) and right align them and then try and match them up,
and when we trying and  matching them up, we're either looking at the exact match or a `1`.
'''
# Shape:

# xs  2 3 4 
# ys      2
# ys    2 3
# ys    3 4
# ys  2 1 1

In [ ]:
# Example of Broadcasting rule:

from numpy import newaxis, broadcast_to
from numpy.random import default_rng

rng = default_rng(0)

xs = rng.normal(size=(2,3,4)).round(1)
ys = rng.normal(size=2).round(1)[:, newaxis, newaxis]
zs = rng.normal(size=(3,4)).round(1)


print(
    xs,
    f'xs.shape                          ={xs.shape}',  #:-> Shape(2, 3, 4) 2:layers 3:rows 4:columns
    f'xs.strides                        ={xs.strides}', #:-> to move from 1 layer to another we skip 96bytes, to go from row to row we skip 32bytes and to go from column to column we skip 8 bytes
    f'xs[0].strides                     ={xs[0].strides}',
    f'xs[0, 1].strides                  ={xs[0, 1].strides}',
    f'xs[:, 1].strides                  ={xs[0, 1].strides}',
    f'ys.strides                        ={ys.strides}',
    f'broadcast_to(zs, xs.shape).strides={broadcast_to(zs, xs.shape).strides}',
    sep='\n',
)


[[[ 0.1 -0.1  0.6  0.1]
  [-0.5  0.4  1.3  0.9]
  [-0.7 -1.3 -0.6  0. ]]

 [[-2.3 -0.2 -1.2 -0.7]
  [-0.5 -0.3  0.4  1. ]
  [-0.1  1.4 -0.7  0.4]]]
xs.shape                          =(2, 3, 4)
xs.strides                        =(96, 32, 8)
xs[0].strides                     =(32, 8)
xs[0, 1].strides                  =(8,)
xs[:, 1].strides                  =(8,)
ys.strides                        =(8, 0, 0)
broadcast_to(zs, xs.shape).strides=(0, 32, 8)


- `strides`: https://numpy.org/doc/stable/reference/generated/numpy.ndarray.strides.html
- `broadcast_to`:https://numpy.org/doc/stable/reference/generated/numpy.broadcast_to.html

What we get from this strides is that the outer-most axis (xs.strides=(96,32,8), so `8` is the mostly tightly packed; these are the values that are most contiguous in memory; that's probably why we choose to `right-align` them because we want to start from things that are most contiguous in memory to thigns that are least contiguous in memory so, that we're not jumping around memory too much!


When we try to figure out  how indexing works by asking `xs[0].strides `: the indexing work from outermost to innermost ; we're drilling down into the data but we always want to get the thing thats as contiguous as possible because that'll be gonna as fast as possible!

**Broadcasting: Works from the right-hand side** \\
**Indexing: Works from the left-hand side**

### Rules of " index alignment "

- It's all about "matching things up"!

In [ ]:
# Without any duplicates in the `.index`


from pandas import Series, Index
from numpy.random import default_rng
from inspect import signature

rng = default_rng(0)

idx1 = [*'abcd']
s1 = Series(rng.integers(-10, +10, size=len(idx1)), index=idx1)

idx2 = [*'abcd']
s2 = Series(rng.integers(-10, +10, size=len(idx2)), index=idx2)


print(
    s1,
    s2,
    f's1.index.has_duplicates={s1.index.has_duplicates}',
    f's2.index.has_duplicates={s2.index.has_duplicates}',
    s1 + s2,
    sep='\n'

)

a    7
b    2
c    0
d   -5
dtype: int64
a    -4
b   -10
c    -9
d   -10
dtype: int64
s1.index.has_duplicates=False
s2.index.has_duplicates=False
a     3
b    -8
c    -9
d   -15
dtype: int64


In [ ]:
from pandas import Series, Index
from numpy.random import default_rng
from inspect import signature

rng = default_rng(0)

idx1 = [*'abcd']
s1 = Series(rng.integers(-10, +10, size=len(idx1)), index=idx1)

idx2 = [*'bcde']
s2 = Series(rng.integers(-10, +10, size=len(idx2)), index=idx2)


print(
    s1,
    s2,
    f's1.index.has_duplicates       = {s1.index.has_duplicates}',
    f's2.index.has_duplicates       = {s2.index.has_duplicates}',
    s1 + s2,
    f's1.index.get_indexer(s2.index)= {s1.index.get_indexer(s2.index)}', # can ask pandas that if we gonna do an operation b/w one index and other then what will happen!
                                                                        # Return:-> s1.index.get_indexer(s2.index)=[ 1  2  3 -1] , where `-1` means filling that column with NaN
    f's2.index.get_indexer(s1.index)= {s2.index.get_indexer(s1.index)}',
    f'Index([*"bcde"]).get_indexer(Index([*"abcd"]), method="bfill")={Index([*"bcde"]).get_indexer(Index([*"abcd"]), method="bfill")}',
    f'Index([*"bcde"]).get_indexer(Index([*"cdef"]), method="bfill")={Index([*"bcde"]).get_indexer(Index([*"cdef"]), method="ffill")}', 
    f'Index([0, 1, 2, 3]).get_indexer(Index([0, 1.1, 2.2, 3.3]), method="nearest")={Index([0, 1, 2, 3]).get_indexer(Index([0, 1.1, 2.2, 3.3]), method="nearest")}',
    f'signature(s1.add)={signature(s1.add)}',                                                                  
    sep='\n',

)

a    7
b    2
c    0
d   -5
dtype: int64
b    -4
c   -10
d    -9
e   -10
dtype: int64
s1.index.has_duplicates       = False
s2.index.has_duplicates       = False
a     NaN
b    -2.0
c   -10.0
d   -14.0
e     NaN
dtype: float64
s1.index.get_indexer(s2.index)= [ 1  2  3 -1]
s2.index.get_indexer(s1.index)= [-1  0  1  2]
Index([*"bcde"]).get_indexer(Index([*"abcd"]), method="bfill")=[0 0 1 2]
Index([*"bcde"]).get_indexer(Index([*"cdef"]), method="bfill")=[1 2 3 3]
Index([0, 1, 2, 3]).get_indexer(Index([0, 1.1, 2.2, 3.3]), method="nearest")=[0 1 2 3]
signature(s1.add)=(other, level=None, fill_value=None, axis=0)


`inspect module`: https://docs.python.org/3/library/inspect.html

`index.get_indexer`: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Index.get_indexer.html \\


### Relation b/w `collections.Counter` and `pandas.Series`:

-  `collections.Counter` is a first-order approximation of  `pandas.Series`

- Supporting only a single-level, unique, hashable object `.index` and non-negative Python int data.


In [ ]:
from collections import Counter 

c1 = Counter('abcd')
c2 = Counter('abcd')
#c2 = Counter('bcde')

print(
    c1,
    c2,
    c1 + c2,
    sep='\n',
)

Counter({'a': 1, 'b': 1, 'c': 1, 'd': 1})
Counter({'a': 1, 'b': 1, 'c': 1, 'd': 1})
Counter({'a': 2, 'b': 2, 'c': 2, 'd': 2})


In [ ]:
c1 = Counter('abcd')
#c2 = Counter('abcd')
c2 = Counter('bcde')

print(
    c1,
    c2,
    c1 + c2,
    sep='\n',
)

Counter({'a': 1, 'b': 1, 'c': 1, 'd': 1})
Counter({'b': 1, 'c': 1, 'd': 1, 'e': 1})
Counter({'b': 2, 'c': 2, 'd': 2, 'a': 1, 'e': 1})


If there are duplicates, consider what is a reasonable way to "match things up"

In [ ]:
from pandas import Series, Index 
from numpy.random import default_rng 

rng = default_rng(0)

idx1 = [*'abcd']
s1 = Series(rng.integers(-10, +10, size=len(idx1)), index=idx1)

# Case with duplicates on 1 side 
idx2 = [*'aabc']
s2 = Series(rng.integers(-10, +10, size=len(idx2)), index=idx2)

print(
    s1,

    s2,
    f's1.index.has_duplicates={s1.index.has_duplicates}',
    f's2.index.has_duplicates={s2.index.has_duplicates}',
    s1 + s2,
    sep='\n{}\n'.format('\N{box drawings light horizontal}' * 40),

)

a    7
b    2
c    0
d   -5
dtype: int64
────────────────────────────────────────
a    -4
a   -10
b    -9
c   -10
dtype: int64
────────────────────────────────────────
s1.index.has_duplicates=False
────────────────────────────────────────
s2.index.has_duplicates=True
────────────────────────────────────────
a     3.0
a    -3.0
b    -7.0
c   -10.0
d     NaN
dtype: float64


we can see that when we add s1+s2 and where we've duplicate the index alignment performs a [`cartesian product`](https://en.wikipedia.org/wiki/Cartesian_product) so,a=7(s1) get added to a= -4(s2) to get 3 and a=7(s1) also goes to a=-10(s2) to get -3.

In [ ]:
# case with duplicates on both sides


from pandas import Series, Index 
from numpy.random import default_rng 

rng = default_rng(0)

idx1 = [*'aacd']
s1 = Series(rng.integers(-10, +10, size=len(idx1)), index=idx1)

# Case with duplicates on 1 side 
idx2 = [*'aabc']
s2 = Series(rng.integers(-10, +10, size=len(idx2)), index=idx2)

print(
    s1,

    s2,
    f's1.index.has_duplicates={s1.index.has_duplicates}',
    f's2.index.has_duplicates={s2.index.has_duplicates}',
    s1 + s2,
    sep='\n{}\n'.format('\N{box drawings light horizontal}' * 40),

)

a    7
a    2
c    0
d   -5
dtype: int64
────────────────────────────────────────
a    -4
a   -10
b    -9
c   -10
dtype: int64
────────────────────────────────────────
s1.index.has_duplicates=True
────────────────────────────────────────
s2.index.has_duplicates=True
────────────────────────────────────────
a     3.0
a    -3.0
a    -2.0
a    -8.0
b     NaN
c   -10.0
d     NaN
dtype: float64


Here, we will do the cartesian product of everywhere we see duplicates (2 a's in s1 and 2 a's in s2) will result in 4 a's in the results for that a!

**Remember**: Pandas `.index` is not guranteed to be **unique**, **sorted**(its not a primary key!), its just some mechanism to look at the data!

In [ ]:
# Example of non-unique index

from pandas import to_datetime, to_timedelta, Series, DataFrame
from numpy import isclose
from numpy.random import default_rng 

rng = default_rng(0)

idx = to_datetime('2022-01-01') + to_timedelta(rng.integers(0, 60*60, size=1_000).cumsum(), unit='s')
s = Series(rng.normal(loc=1, scale=.1, size=len(idx)).cumprod(), index=idx)

# Doing index manipulation
print(
    s,
    s.resample('1T').mean(),# resampling in-terms of `every-minute`
    s.groupby(s.index.round('1T')).mean(), # grouping these value by time rounded to the min and then performing the mean
    s.resample('1T').agg(set), # same as the first-opertion but we put values into a `set` this time
    s.resample('1T').agg(lambda s: {*s.index}), #instead of putting values; we're putting index contents into set!
    s.groupby(s.index.round('1T')).agg(lambda s: {*s.index}), # Doing same thing as above with groupby
    DataFrame({
        'resample': s.resample('1T').agg(lambda s: {*s.index}),
        'groupby': s.groupby(s.index.round('1T')).agg(lambda s: {*s.index}),
    }), # Putting our two above commands into a DataFrame so that we can check the difference!
    DataFrame({
        'resample': s.resample('1T').agg(lambda s: {*s.index}),
        'groupby': s.groupby(s.index.round('1T')).agg(lambda s: {*s.index}),
        
    }).apply(lambda s: s['resample'] == s['groupby'], axis='columns'),  # taking the above DataFrame and checking what they have in common 
    (comp_idx := DataFrame({
            'resample': (rs := s.resample('1T').agg(lambda s: {*s.index})),
        'groupby': (gb := s.groupby(s.index.round('1T')).agg(lambda s: {*s.index})),
        
    }).apply(lambda s: s['resample'] == s['groupby'], axis='columns')),  # we're taking the index of the above result by iteself!
    comp_idx.where(comp_idx).index,  # and then we can index this thing where its `True`, will show all the places where results matched up!
    same_idx := comp_idx[comp_idx].index,  # computing same indicies 
    f'{(rs.loc[same_idx] == gb.loc[same_idx]).all =}', #looking at `groupby ` and`resample` where the same indicies are on anywhere where they joined on the same value!
    common_idx := rs.index.intersection(gb.index),
    diff_idx := common_idx.difference(same_idx), # take the orignial indicies of everything they both have and then subtract out everywhere where they are different
    f'{(rs.loc[diff_idx] != gb.loc[diff_idx]).all() =}',
        


    sep='\n{}\n'.format('\N{box drawings light horizontal}' * 60),
   
)

'''
The reason,we went through all this operations is for cases like where you've a very large datasets and its not common for us do various index operations on them (and if we're not 
using index then we're making a lots of copy of raw_Data ; which consumes a lot of memory!). Instead, a better way will be to take two datasets(or more) and figure out what samples 
are included in each bucket, find all the bucket where they're same and then compute all the places where they used the same bucket and where they used different bucket; then go back 
to original dataset to figure out whats the corresponding calculation was for those buckets
'''





2022-01-01 00:51:00     True
2022-01-01 00:52:00    False
2022-01-01 00:53:00    False
2022-01-01 00:54:00    False
2022-01-01 00:55:00    False
                       ...  
2022-01-22 11:45:00    False
2022-01-22 11:46:00    False
2022-01-22 11:47:00    False
2022-01-22 11:48:00    False
2022-01-22 11:49:00     True
Freq: T, Length: 30899, dtype: bool
────────────────────────────────────────────────────────────
DatetimeIndex(['2022-01-01 00:51:00', '2022-01-01 00:52:00',
               '2022-01-01 00:53:00', '2022-01-01 00:54:00',
               '2022-01-01 00:55:00', '2022-01-01 00:56:00',
               '2022-01-01 00:57:00', '2022-01-01 00:58:00',
               '2022-01-01 00:59:00', '2022-01-01 01:00:00',
               ...
               '2022-01-22 11:40:00', '2022-01-22 11:41:00',
               '2022-01-22 11:42:00', '2022-01-22 11:43:00',
               '2022-01-22 11:44:00', '2022-01-22 11:45:00',
               '2022-01-22 11:46:00', '2022-01-22 11:47:00',
               '

`.cumsum()`:https://pandas.pydata.org/docs/reference/api/pandas.Series.cumsum.html  \
`.cumprod()`:https://pandas.pydata.org/docs/reference/api/pandas.Series.cumprod.html \
`:=`  a.k.a "walrus Operator": https://realpython.com/python-walrus-operator/ 

### Looking at Pandas `DataFrame`

In [ ]:
from pandas import DataFrame, date_range
from numpy import repeat, tile
from numpy.random import default_rng
from string import ascii_lowercase

rng = default_rng(0)

tickers = rng.choice([*ascii_lowercase], size=(100,4)).view('<U4').ravel()
dates = date_range('2022-01-01', '2022-12-31', name='date')
prices = (
    100 * rng.random(size=len(tickers))
    * rng.normal(loc=1, scale=0.01, size=(len(dates), len(tickers))).cumprod(axis=0)
).ravel()
volumes = rng.integers(-50_000, +50_000, size=len(dates) * len(tickers)).round(-2)

df = DataFrame({
    'date' : repeat(dates, len(tickers)),
    'ticker': tile(tickers, len(dates)),
    'price': prices,
    'volume': volumes,


})#.set_index(['date', 'ticker'])  # If we un-comment this then we can see that we have two 1D data `price` and `volume` on same index `date` and `ticker`

print(
    df.head(3),
    df.loc[0, 'ticker'], # return element at label `0` and ticekr column
    df.iloc[0, 0], # return element at position `0` and column`0`
    df.loc[0]['ticker'], # same as df.loc[0].loc['ticker']
    df.loc[0],
    df.loc[:, 'ticker'], # returns everyhting for the `ticker` column and for every particualr row
    sep='\n',
)


        date ticker      price  volume
0 2022-01-01   wqnh  32.147952  -39700
1 2022-01-01   ibba  18.696088    8400
2 2022-01-01   evqx  67.455290  -44800
wqnh
2022-01-01 00:00:00
wqnh
date      2022-01-01 00:00:00
ticker                   wqnh
price               32.147952
volume                 -39700
Name: 0, dtype: object
0        wqnh
1        ibba
2        evqx
3        npzs
4        qooy
         ... 
36495    tfun
36496    tnhc
36497    nzao
36498    laou
36499    tznp
Name: ticker, Length: 36500, dtype: object


`.tile()` : https://numpy.org/doc/stable/reference/generated/numpy.tile.html \
`.ravel()`: https://numpy.org/doc/stable/reference/generated/numpy.ravel.html#numpy.ravel 


A `Series` is singly-indexed one-dimensional data \
A `DataFrame` is doubly-indexed \
The `DataFrame` is a doubly-indexed collection of like-indexed one-dimensional data \

Thus, `Pandas` is really just an indexed 1D data  like `Series` or a collection of liked indexed 1D data like `DataFrame`  \

Real 2D data is for eg an image, where if we roate it then there is a slight change in that image but the fundamental meaning reamins the same  \
whereas in pandas if we rotate the data then we end up with something entirely new!



In [ ]:
from pandas import DataFrame 
from numpy.random import default_rng 

rng = default_rng(0)

df = DataFrame(rng.normal(size=(5, 3)).round(2))

# idx = [0, 0, 1, 1, 2]
# df = DataFrame(rng.normal(size=(len(idx),3)).round(2), index=idx)
# df.columns = [0, 1, 1]


print(
    df,
    df.loc[0], # access one row of the dataframe ; return to as pandas series
    f'{type(df.loc[0]) = }',
    df[0], # access one column
    f'{type(df[0]) = }',
    f'{type(df.loc[0]) = }', # This will return a Pandas `Series`
    f'{type(df.loc[2]) = }', # This will return a Pandas `Series`


    sep='\n{}\n'.format('\N{box drawings light horizontal}' * 60),
)

      0     1     2
0  0.13 -0.13  0.64
1  0.10 -0.54  0.36
2  1.30  0.95 -0.70
3 -1.27 -0.62  0.04
4 -2.33 -0.22 -1.25
────────────────────────────────────────────────────────────
0    0.13
1   -0.13
2    0.64
Name: 0, dtype: float64
────────────────────────────────────────────────────────────
type(df.loc[0]) = <class 'pandas.core.series.Series'>
────────────────────────────────────────────────────────────
0    0.13
1    0.10
2    1.30
3   -1.27
4   -2.33
Name: 0, dtype: float64
────────────────────────────────────────────────────────────
type(df[0]) = <class 'pandas.core.series.Series'>
────────────────────────────────────────────────────────────
type(df.loc[0]) = <class 'pandas.core.series.Series'>
────────────────────────────────────────────────────────────
type(df.loc[2]) = <class 'pandas.core.series.Series'>


But if we change the `index` then let see the change in `f'{type(df.loc[0]) = }'` will show

In [ ]:
from pandas import DataFrame 
from numpy.random import default_rng 

rng = default_rng(0)

df = DataFrame(rng.normal(size=(5, 3)).round(2))

idx = [0, 0, 1, 1, 2]
df = DataFrame(rng.normal(size=(len(idx),3)).round(2), index=idx)
df.columns = [0, 1, 1]


print(
    df,
    # df.loc[0], # access one row of the dataframe ; return to as pandas series
    # f'{type(df.loc[0]) = }',
    # df[0], # access one column
    # f'{type(df[0]) = }',
    # f'{type(df.loc[0]) = }', # This will return a Pandas `DataFrame` instead of a series now because we have two rows with `0`!
    # f'{type(df.loc[2]) = }', # This will return a Pandas `Series` because they are not two values at the position !
    
    
    # Why  `.iloc` is a very useful tool in such scenarios :

    # - `iloc` is unambiguous, it always represent the value a physical positon , thus `.iloc[0]` always means at physical position `0`
    #     and there can't be two physical position `0`.
    # - `.iloc` can be thought as an unique range-index starting from  unit`0` to the size of your structure!
    
    f'{df.iloc[0] = }',
    f'{type(df.iloc[0])}',
    f'{df.iloc[0].index = }', # This means that if the orginial df is index on the columns[0,1,1] and rows[0,0,1,2] and I asked for row'0'; 
                                # the indexing of the result will take the column index(That is why its doubly-indexed in Dataframe):-> Use column index when we look at the rows
                                # and rows index when we look at the columns
    f'{df.iloc[0].name = }',
    # df.iloc[2],
    # f'{df.iloc[2].index = }',
    # f'{df.iloc[2].name = }',
    f'{df[0] = }',
    f'{df[0].index =}',
    f'{df[0].name =}',

    df.iloc[0][0], # By label
    df[0][3:], # by position

    sep='\n{}\n'.format('\N{box drawings light horizontal}' * 60),
)

      0     1     1
0 -0.73 -0.54 -0.32
0  0.41  1.04 -0.13
1  1.37 -0.67  0.35
1  0.90  0.09 -0.74
2 -0.92 -0.46  0.22
────────────────────────────────────────────────────────────
df.iloc[0] = 0   -0.73
1   -0.54
1   -0.32
Name: 0, dtype: float64
────────────────────────────────────────────────────────────
<class 'pandas.core.series.Series'>
────────────────────────────────────────────────────────────
df.iloc[0].index = Int64Index([0, 1, 1], dtype='int64')
────────────────────────────────────────────────────────────
df.iloc[0].name = 0
────────────────────────────────────────────────────────────
df[0] = 0   -0.73
0    0.41
1    1.37
1    0.90
2   -0.92
Name: 0, dtype: float64
────────────────────────────────────────────────────────────
df[0].index =Int64Index([0, 0, 1, 1, 2], dtype='int64')
────────────────────────────────────────────────────────────
df[0].name =0
────────────────────────────────────────────────────────────
-0.73
───────────────────────────────────────────────────────

### `SettingWithCopyWarning` in Pandas

In [ ]:
from pandas import DataFrame 
from numpy.random import default_rng 
from string import ascii_lowercase 
from warnings import catch_warnings, filterwarnings 


rng = default_rng(0)

df = DataFrame({
    'a' : rng.integers(-10, +10, size=(size := 5)),
    'b' : rng.normal(size=size).round(2),
    'c' : rng.choice([*ascii_lowercase],size=size),

})

# Uncomment each at a time to see the behaviour!
with catch_warnings():
    filterwarnings('error')
    # df.iloc[0]['c'] = 'z'                     # This return an error

    # df.iloc[0, 'c'] = 'z'                     # This works! 
    # df.iloc[0, df.columns.get_loc('c')] = 'z' # This works!
    # df.loc[df.index.get_loc(0), 'c'] = 'z'    # This works!



print(
    df,
    df.iloc[0],
    f'{type(df.iloc[0]) = }',
    f'{df.iloc[0].dtype = }',
    sep='\n{}\n'.format('\N{box drawings light horizontal}' * 60)
)

   a     b  c
0  7  0.10  z
1  2 -0.54  q
2  0  0.36  o
3 -5  1.30  o
4 -4  0.95  y

a      7
b    0.1
c      z
Name: 0, dtype: object

type(df.iloc[0]) = <class 'pandas.core.series.Series'>

df.iloc[0].dtype = dtype('O')


In [ ]:
from pandas import DataFrame 
from numpy.random import default_rng 
from string import ascii_lowercase 



rng = default_rng(0)

df = DataFrame({
    'a' : rng.integers(-10, +10, size=(size := 5)),
    'b' : rng.normal(size=size).round(2),
    'c' : rng.choice([*ascii_lowercase],size=size),

})

print(
    df,
    df._data,
    df.index,   # Also called as `row-index` or the `major-axis`
    df.columns, # Also called as `column-index` or the `minor-axis`
    sep='\n{}\n'.format('\N{box drawings light horizontal}' * 60)

)

   a     b  c
0  7  0.10  b
1  2 -0.54  q
2  0  0.36  o
3 -5  1.30  o
4 -4  0.95  y
────────────────────────────────────────────────────────────
BlockManager
Items: Index(['a', 'b', 'c'], dtype='object')
Axis 1: RangeIndex(start=0, stop=5, step=1)
NumericBlock: slice(0, 1, 1), 1 x 5, dtype: int64
NumericBlock: slice(1, 2, 1), 1 x 5, dtype: float64
ObjectBlock: slice(2, 3, 1), 1 x 5, dtype: object
────────────────────────────────────────────────────────────
RangeIndex(start=0, stop=5, step=1)
────────────────────────────────────────────────────────────
Index(['a', 'b', 'c'], dtype='object')


### Finally! what are the rules of `index alignment` on `DataFrame`?

In [ ]:
from pandas import DataFrame, Series, date_range, concat
from numpy.random import default_rng

# rng = default_rng(0)
# size = 5
# data = {'a' : rng.integers(-10, +10, size=size), 'b' : rng.integers(-10, +10, size=size), 'c' : rng.integers(-10, +10, size=size)}

# df1 = DataFrame(data, index=date_range('2022-01-01', periods=size, name='date') )
# df2 = DataFrame(data, index=date_range('2022-01-02', periods=size, name='date'))


#You can write your `DataFrame`` this way or comment this and un-comment the above part! I personally like this way :)
rng = default_rng(0)
size = 5
df1 = DataFrame(
    {
    'a' : rng.integers(-10, +10, size=size),
    'b' : rng.integers(-10, +10, size=size),
    'c' : rng.integers(-10, +10, size=size),
    },
    index=date_range('2022-01-01', periods=size, name='date')
    )

df2 = DataFrame(
    {
    'a' : rng.integers(-10, +10, size=size),
    'b' : rng.integers(-10, +10, size=size),
    'c' : rng.integers(-10, +10, size=size),
    # 'd' : rng.integers(-10, +10, size=size),
    }, 
    index=date_range('2022-01-02', periods=size, name='date')
)


print(
    df1,
    df2,
    df1+df2, # will get NaN's at the top and bottom because we're missing `2022-01-01` in df2 and `2022-01-06` from df1 but since columns are the same; it gonna match columns by name!

    sep='\n\n',

)

            a   b  c
date                
2022-01-01  7 -10  2
2022-01-02  2  -9  8
2022-01-03  0 -10  0
2022-01-04 -5  -7  2
2022-01-05 -4   6  9

            a   b   c
date                 
2022-01-02  4  -5   7
2022-01-03  2   6   1
2022-01-04  0   3 -10
2022-01-05  1 -10   5
2022-01-06  8  -3   4

              a     b     c
date                       
2022-01-01  NaN   NaN   NaN
2022-01-02  6.0 -14.0  15.0
2022-01-03  2.0  -4.0   1.0
2022-01-04 -5.0  -4.0  -8.0
2022-01-05 -3.0  -4.0  14.0
2022-01-06  NaN   NaN   NaN


In [ ]:
# adding Extra Column!

rng = default_rng(0)
size = 5
df1 = DataFrame(
    {
    'a' : rng.integers(-10, +10, size=size),
    'b' : rng.integers(-10, +10, size=size),
    'c' : rng.integers(-10, +10, size=size),
    },
    index=date_range('2022-01-01', periods=size, name='date')
    )

df2 = DataFrame(
    {
    'a' : rng.integers(-10, +10, size=size),
    'b' : rng.integers(-10, +10, size=size),
    'c' : rng.integers(-10, +10, size=size),
    'd' : rng.integers(-10, +10, size=size),
    }, 
    index=date_range('2022-01-02', periods=size, name='date')
)


print(
    df1,
    df2,
    df1+df2, # This will result in getting `NaN's` in top and bottom as above but with addition of getting NaN in the extra column `d` ! 

    sep='\n\n',

)

            a   b  c
date                
2022-01-01  7 -10  2
2022-01-02  2  -9  8
2022-01-03  0 -10  0
2022-01-04 -5  -7  2
2022-01-05 -4   6  9

            a   b   c   d
date                     
2022-01-02  4  -5   7   6
2022-01-03  2   6   1  -7
2022-01-04  0   3 -10  -9
2022-01-05  1 -10   5   7
2022-01-06  8  -3   4 -10

              a     b     c   d
date                           
2022-01-01  NaN   NaN   NaN NaN
2022-01-02  6.0 -14.0  15.0 NaN
2022-01-03  2.0  -4.0   1.0 NaN
2022-01-04 -5.0  -4.0  -8.0 NaN
2022-01-05 -3.0  -4.0  14.0 NaN
2022-01-06  NaN   NaN   NaN NaN


In [ ]:
from pandas import DataFrame, Series, date_range
from numpy.random import default_rng 

rng = default_rng(0)
size = 5
df = DataFrame(
    {
    'a' : rng.integers(-10, +10, size=size),
    'b' : rng.integers(-10, +10, size=size),
    'c' : rng.integers(-10, +10, size=size),
    },
    index=date_range('2022-01-01', periods=size, name='date')
    )

s = Series(rng.integers(-10, +10, size=len(df)), index=df.index)

print(
    df,
    s,
    # df + s, # took the `row-index` of the `Series` and try to match against the columns ; will give the same result for `s + df`
    # df + s.T, # Transpose dosen't work  because the transposition of a pandas `Series` is the `Series` itself! Will show a similar result for `(df.T + s).T`
    sep='\n\n',

)




            a   b  c
date                
2022-01-01  7 -10  2
2022-01-02  2  -9  8
2022-01-03  0 -10  0
2022-01-04 -5  -7  2
2022-01-05 -4   6  9

date
2022-01-01    4
2022-01-02    2
2022-01-03    0
2022-01-04    1
2022-01-05    8
Freq: D, dtype: int64


In [ ]:
from pandas import DataFrame, Series, date_range
from numpy.random import default_rng 

rng = default_rng(0)
size = 5
df = DataFrame(
    {
    'a' : rng.integers(-10, +10, size=size),
    'b' : rng.integers(-10, +10, size=size),
    'c' : rng.integers(-10, +10, size=size),
    },
    index=date_range('2022-01-01', periods=size, name='date')
    )

s = Series(rng.integers(-10, +10, size=len(df.columns)), index=df.columns) # Same `Series` but the index is equal to `columns-indexing` of our `DataFrame`

print(
    df,
    s,
    df + s, # Now we add these together!

    sep='\n\n',

)


            a   b  c
date                
2022-01-01  7 -10  2
2022-01-02  2  -9  8
2022-01-03  0 -10  0
2022-01-04 -5  -7  2
2022-01-05 -4   6  9

a    4
b    2
c    0
dtype: int64

             a  b  c
date                
2022-01-01  11 -8  2
2022-01-02   6 -7  8
2022-01-03   4 -8  0
2022-01-04  -1 -5  2
2022-01-05   0  8  9


In [ ]:
from pandas import DataFrame, date_range, IndexSlice, Series 
from numpy import repeat, tile 
from numpy.random import default_rng 
from string import ascii_lowercase 

rng = default_rng(0)

tickers = rng.choice([*ascii_lowercase], size=(100,4)).view('<U4').ravel()
dates = date_range('2022-01-01', '2022-12-31', name='date')
prices = (
    100 * rng.random(size=len(tickers))
    * rng.normal(loc=1, scale=0.01, size=(len(dates), len(tickers))).cumprod(axis=0)
).ravel()
volumes = rng.integers(-50_000, +50_000, size=len(dates) * len(tickers)).round(-2)

df = DataFrame({
    'date' : repeat(dates, len(tickers)),
    'ticker' : tile(tickers, len(dates)),
    'price' : prices,
    'volume' : volumes,
}).set_index(['date', 'ticker']).sort_index()

factor = Series(
    rng.normal(loc=1, scale=.1, size=len(tickers)),
    index=tickers,
    name='factor', 
)
factor.index.name = 'ticker'

print(
    # df,
    factor, # Only index by ticker!
    df['price'], # This has multi-index, both by `date` and `ticker`
    # df.head(3),
    # df.loc[IndexSlice[:, 'arnq', :]].sample(3),
    # factor.head(3),
    df['price'] * factor, # Pandas is smart enough to figure out by matching each one in the factor to everyone in the price
                          # Would have taken us so much of PythonCode+looping if we try to built it manually! Thanks Pandas team!!  
    sep='\n\n',

)

ticker
wqnh    0.998365
ibba    0.853698
evqx    1.063613
npzs    1.009087
qooy    0.962868
          ...   
tfun    1.004738
tnhc    1.168481
nzao    1.063286
laou    0.913663
tznp    1.071009
Name: factor, Length: 100, dtype: float64

date        ticker
2022-01-01  arnq       38.749610
            awkb       96.332418
            awyd       85.292694
            bcjv       87.471962
            bjqc        9.247532
                         ...    
2022-12-31  yqjz       48.747306
            ysia      123.215568
            zglo       85.323680
            zhnw       51.300465
            zyrz       58.677036
Name: price, Length: 36500, dtype: float64

date        ticker
2022-01-01  arnq       37.132688
            awkb       90.844435
            awyd       86.337632
            bcjv       79.312476
            bjqc        9.923136
                         ...    
2022-12-31  yqjz       53.585677
            ysia      118.010350
            zglo       74.540744
            zhnw     

In [ ]:
# Example of Multi-Index !

from pandas import Series , MultiIndex, period_range, IndexSlice 
from numpy.random import default_rng 

rng = default_rng(0)

s = Series(
    index=(idx := MultiIndex.from_product([
        period_range('2022Q1', periods=4, freq='Q', name='quarter'),
        ['abc', 'def', 'xyz'],
    ], names=['quarter', 'symbol'])),
    data=rng.integers(-10, +10, size=len(idx)),
)

print(
    s,
    s.index,
    s.loc['2022Q1'],
    s.loc['2022Q1', 'abc'],
    s.loc[IndexSlice['2022Q2', ['abc', 'xyz'], :]],
    s.loc[IndexSlice['2022-03-01':, ['abc', 'xyz'], :]],
    sep='\n\n',

)

quarter  symbol
2022Q1   abc        7
         def        2
         xyz        0
2022Q2   abc       -5
         def       -4
         xyz      -10
2022Q3   abc       -9
         def      -10
         xyz       -7
2022Q4   abc        6
         def        2
         xyz        8
dtype: int64

MultiIndex([('2022Q1', 'abc'),
            ('2022Q1', 'def'),
            ('2022Q1', 'xyz'),
            ('2022Q2', 'abc'),
            ('2022Q2', 'def'),
            ('2022Q2', 'xyz'),
            ('2022Q3', 'abc'),
            ('2022Q3', 'def'),
            ('2022Q3', 'xyz'),
            ('2022Q4', 'abc'),
            ('2022Q4', 'def'),
            ('2022Q4', 'xyz')],
           names=['quarter', 'symbol'])

symbol
abc    7
def    2
xyz    0
dtype: int64

7

quarter  symbol
2022Q2   abc       -5
         xyz      -10
dtype: int64

quarter  symbol
2022Q1   abc        7
         xyz        0
2022Q2   abc       -5
         xyz      -10
2022Q3   abc       -9
         xyz       -7
2022Q4   abc       

### `MultiIndex` is not the only hierarchical `Index`!

In [ ]:
from pandas import Series, date_range 
from numpy.random import default_rng 

rng = default_rng(0)

s = Series(
    index=(idx := date_range('2022-01-01', periods=6, name= 'date', freq='14D')),
    data=rng.integers(-10, +10, size=len(idx)),
)
# `DatetimeIndex` is actually a `MultiIndex` where each level is each fidelity of time measurement [year, month , day and so on..]
print(
    s,
    s.index,
    s.loc['2022'], # If we just ask for the year then this will return all the rows for that year just like `MultiIndex` for just one layer of that Index
    s.loc['2022-01'], # `DatetimeIndex` is same as MultiIndex with 3-levels : Year-Month-Day ; stored as one particular `Index` and without syntax of `MultiIndex`
    sep='\n\n',

)

date
2022-01-01     7
2022-01-15     2
2022-01-29     0
2022-02-12    -5
2022-02-26    -4
2022-03-12   -10
Freq: 14D, dtype: int64

DatetimeIndex(['2022-01-01', '2022-01-15', '2022-01-29', '2022-02-12',
               '2022-02-26', '2022-03-12'],
              dtype='datetime64[ns]', name='date', freq='14D')

date
2022-01-01     7
2022-01-15     2
2022-01-29     0
2022-02-12    -5
2022-02-26    -4
2022-03-12   -10
Freq: 14D, dtype: int64

date
2022-01-01    7
2022-01-15    2
2022-01-29    0
Freq: 14D, dtype: int64


### Operations in `pandas` should be thought in-terms of how they operate on or affect the `.index`

In [ ]:
from pandas import Series, date_range 
from numpy.random import default_rng 
from scipy.stats import zscore, kurtosis

rng = default_rng(0)

s = Series(
    index=(idx := date_range('2022-01-01', periods=1_000, name= 'date', freq='D')),
    data=rng.integers(-10, +10, size=len(idx)),
)

print(
    # s, # Series indexd on individual days
    # s.groupby(s.index.month).mean(), # Group it by month and take the mean
    # s.groupby(s.index.to_period('M')).mean(), # Map actual dates to months!
    # s.groupby(s.index.to_period('M')).mean().loc['2022-02-14':'2022-05-01'],
    # s.groupby(s.index.to_period('M')).agg(lambda s: s.skew()), # if we want our groups to become the new `index` then we use `.agg()`; 
    #                                                             #`.agg()` takes the groups & collaspe them into one scalar value(that is indexed on each of the groups)
    # s.groupby(s.index.to_period('M')).transform(zscore), # `.transform()` is about preserving  orginal indexing
    s.groupby(s.index.to_period('M')).apply(lambda df: df[df > 0].cumsum()), # `.apply` is about creating brand-new `index` and then concat it into a `pandas df` later on!
    sep='\n\n',
)

# `.agg()` and `.transform` works on `Series` basis while `.apply` works on `DataFrame` basis

date     date      
2022-01  2022-01-01     7
         2022-01-02     9
         2022-01-10    15
         2022-01-11    17
         2022-01-12    25
                       ..
2024-09  2024-09-17    25
         2024-09-20    26
         2024-09-21    27
         2024-09-22    36
         2024-09-26    42
Length: 486, dtype: int64


In [82]:
# More on `DataFrame`

from turtle import title
from pandas import DataFrame , date_range, Series, IndexSlice, to_datetime, MultiIndex 
from numpy import repeat, tile
from numpy.random import default_rng 
from string import ascii_lowercase
from datetime import timedelta 

rng = default_rng(0)

tickers = rng.choice([*ascii_lowercase], size=(100, 4)).view('<U4').ravel()
dates = date_range('2022-01-01', '2022-12-31', name='date')
prices = (
    100 * rng.random(size=len(tickers))
    * rng.normal(loc=1, scale=0.01, size=(len(dates), len(tickers))).cumprod(axis=0)
).ravel()
volumes = rng.integers(-50_000, +50_000, size=len(dates) * len(tickers)).round(-2)

df = DataFrame({
    'date' : repeat(dates, len(tickers)),
    'ticker' : tile(tickers, len(dates)),
    'price' : prices,
    'volume' : volumes,
}).set_index(['date', 'ticker']).sort_index()


print(
    # df.head(3),
    # df.index, df.columns, 
    # df.axes,              # `.axes ` is just `index` and`columns` in a tuple
    # df.unstack(),           # unstack the prescribed level(s) from row to column. 
    # df.stack(),           # : stack the prescribed level(s) from column to row.
    # _df := DataFrame({
    #     'sector' : rng.choice(['tech', 'healthcare', 'energy'], size=(size := 5)),
    #     to_datetime('2022-01-01'): rng.normal(size=size),
    #     to_datetime('2022-01-02'): rng.normal(size=size),
    #     to_datetime('2022-01-03'): rng.normal(size=size),
    # }, index=rng.choice([*ascii_lowercase], size=(size, 4)).view('<U4').ravel()),

    # _df.melt(
    #     id_vars=['sector'],
    #     value_vars=_df.columns.difference(['sector']),
    #     ignore_index=False,
    #     var_name='date'

    # ).set_index('date', append=True).sort_index(),  # `melt`:take part of my columns except sector column and move it down into my data
    # df.pivot,
    #df.groupby([df.index.get_level_values('date').to_period('M'), 'ticker']).sum().unstack(),
    # df.pivot_table(
    #     index=df.index.get_level_values('date').to_period('M'),
    #     columns='ticker',
    #     aggfunc='sum',
    # ),
    # df.sort_index(),
    # df.sort_index(axis='columns', ascending=False),
    # df.sort_values('volume'),
    # df.reset_index('ticker'), # `.reset_index()` : takes a layer of the index and pops it back into the data
    # df.reset_index('ticker', drop=True),
    # df.reset_index('ticker').set_index('ticker'),
    # df.reset_index('ticker').set_index('ticker', append=True),
    # df.droplevel('ticker'),
    # df.reindex(date_range('2022-02-01', periods=4, freq='14D'), level='date'),
    # df.set_axis(df.columns.str.title(), axis='columns'),
    # df.rename(str.title, axis='columns'),
    # df.rename(lambda dt: dt - timedelta(days=1), level='date'),
    # df.reorder_levels(['ticker', 'date']),
    # df.swaplevel(),
    # df.rename_axis(['value'], axis='columns'),
    # df.rename_axis(['value'], axis='columns').columns,
    # df.stack().index,
    # df.rename_axis(['value'], axis='columns').stack().index,
    # df.swapaxes('index', 'columns'), # Same as Transpose `df.T`
    # df.squeeze(),
    # df[['price']].squeeze(),
    # df.loc['2022-01-01'].squeeze(axis='index'),
    # _s := Series([*rng.integers(10, size=(3, 3))]),
    # _s.explode(),
    # df.at[('2022-01-01', 'arnq'), 'price'], # same as : `df.loc[('2022-01-01', 'arnq'), 'price']`
    # df.iat[0,0], # same as : `df.iloc[0,0]`,
    # only diff-> `.at`and `.iat()` give scalar values
    # _df1 := DataFrame({
    #     'a' : rng.integers(-10, +10, size=(size := 3)),
    #     'b' : rng.integers(-10, +10, size=size),
    # }, index=date_range('2022-01-01', periods=size)),
    # _df2 := DataFrame({
    #     'b' : rng.integers(-10, +10, size=(size := 3)),
    #     'c' : rng.integers(-10, +10, size=size),
    # }, index=date_range('2022-01-01', periods=size)), 
    # *_df1.align(_df2),
    # *_df1.align(_df2, axis='index'),
    # _df1.join(_df2, lsuffix='1', rsuffix='2'),
    # _df1.join(_df2, lsuffix='1', rsuffix='2',how='outer'),
    #df.merge,
    # df.abs(),
    # df.clip(10, 100),
    # df.min(),
    # df.min(axis='index'),
    # df.min(axis='columns'),
    # df.max(),
    # df.count(),
    # df.nunique(),
    # df.mad(),
    # df.value_counts(),
    # df.nsmallest(1, columns='price'),
    # df.nlargest(3, columns=['volume']),
    # df.loc[df.nsmallest(3, columns='price').index]['volume'], # what are the volume for three smallest values in price column
    # df.idxmax(),
    # df.idxmin(),
    # df.expanding().max(),
    # df.ewm(alpha=.1).mean(),
    # df.shift(1),
    # df.diff(1),
    # df.rolling(3, min_periods=1).mean(),
    # df.resample('M').mean(), # will not work on this dataset because its not a `daytimeIndex`
    # df.resample('M', level='date').mean(), # this is how make it work for this `DataFrame` but it will `groupby ` resample index!
    df.groupby('ticker').apply(
        lambda s: s.resample('M',level='date').mean(),  # this preserve the outer index
    ),




    sep='\n{}\n'.format('\N{box drawings light horizontal}' * 50),


)

# Bottom line : Instead of Memorzing all this operations, better to understand rules of `indexing` and
# then apply them to the operations we need to use! 


                       price        volume
ticker date                               
arnq   2022-01-31  38.698474   2309.677419
       2022-02-28  38.094984  -5392.857143
       2022-03-31  38.173743   7319.354839
       2022-04-30  40.141961  -8283.333333
       2022-05-31  39.877949   3009.677419
...                      ...           ...
zyrz   2022-08-31  66.316170  -3712.903226
       2022-09-30  64.247084   2530.000000
       2022-10-31  62.633014   -919.354839
       2022-11-30  59.078532  12186.666667
       2022-12-31  59.668530  -5664.516129

[1200 rows x 2 columns]


- `Stack and Unstack ` : <https://towardsdatascience.com/reshaping-a-dataframe-with-pandas-stack-and-unstack-925dc9ce1289>

- `.unstack()`: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.unstack.html
- `.stack()` : https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.stack.html#pandas.DataFrame.stack
- `.pivot()`: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.pivot.html#pandas.DataFrame.pivot
- `.melt()`: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.melt.html?highlight=melt#pandas.DataFrame.melt
- `.pivot_table()`: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.pivot_table.html
- `.sort_index()`:https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sort_index.html
- `.sort_values()` : https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sort_values.html
- `.reset_index()`: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.reset_index.html
- `.droplevel()`:https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.droplevel.html
- `.reindex()`: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.reindex.html
- `,reorder_levels()`: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.reorder_levels.html
- `.swaplevel()`:https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.swaplevel.html
- `.rename_axis()` : https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.swaplevel.html
- `.swapaxes()`:https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.swapaxes.html
- `.squeeze()`:https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.squeeze.html
- `.explode()`:https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.explode.html
- `.align()`: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.align.html
- `.join()`:https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.join.html
- `.merge()`:https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html
- `.mad()`:https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.mad.html
- `.value_counts()`:https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.value_counts.html
- `.nsmallest()`:https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.nsmallest.html
- `.nlargest()`:https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.nlargest.html
- `.idxmin()`:https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.idxmin.html
- `.idxmax()` :https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.idxmax.html
- `.expanding()`:https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.expanding.html
- `.ewn()`:https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.ewm.html
- `.rolling`:https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rolling.html
- `.shift()`:https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.shift.html
- `.diff()`:https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.diff.html
- `.resample()`:https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.resample.html



### PersonalExperience: How a  comma(`,`) can mess up your life! 

In [54]:
#Let's create two df's same as the ones that we created for our `DataFrame Index alignment` section!

from pandas import DataFrame, Series, date_range
from numpy.random import default_rng

rng = default_rng(0)
size = 5
df1 = DataFrame(
    {
    'a' : rng.integers(-10, +10, size=size),
    'b' : rng.integers(-10, +10, size=size),
    'c' : rng.integers(-10, +10, size=size),
    },
    index=date_range('2022-01-01', periods=size, name='date')
    ),                                                          # this comman will turn our df into a tuple!

df2 = DataFrame(
    {
    'a' : rng.integers(-10, +10, size=size),
    'b' : rng.integers(-10, +10, size=size),
    'c' : rng.integers(-10, +10, size=size),
    # 'd' : rng.integers(-10, +10, size=size),
    }, 
    index=date_range('2022-01-02', periods=size, name='date')
),                                                              # this comman will turn our df into a tuple!


print(

    # df1,
    # df2,
    df1+df2,
    sep='\n\n',

)

(            a   b  c
date                
2022-01-01  7 -10  2
2022-01-02  2  -9  8
2022-01-03  0 -10  0
2022-01-04 -5  -7  2
2022-01-05 -4   6  9,             a   b   c
date                 
2022-01-02  4  -5   7
2022-01-03  2   6   1
2022-01-04  0   3 -10
2022-01-05  1 -10   5
2022-01-06  8  -3   4)
